### ISSUE TITLE
hakai_salmon_data: lat/lons missing

### ISSUE THREAD

**Issue by albenson-usgs** [marinebon/ioos_bio_data_scripts#2]
There are 138 events missing latitude and longitude in the hakai_salmon_data event file. These events and their associated occurrences can't be included in OBIS. Is it possible to find out what these geolocations are?

**Comment by Br-Johnson** [comment]
This was the result of me including seines that had no fish retained in them. Which means there shouldn't be any occurrences associated with them. But these events don't need to be here so I will filter out the events that didn't catch fish. All seines now have a lat/lon
