### ISSUE TITLE
hakai_salmon_data: samplingEffort blank

### ISSUE THREAD

**Issue by albenson-usgs** [marinebon/ioos_bio_data_scripts#3]
There are no values included in the hakai_salmon_data event file samplingEffort field. Is there a reason to include a field with no data?

**Comment by Br-Johnson** [comment]
I included it to make it clear that there is no quantitative measure for `samplingEffort` associated with this data. If I left the column out, it might seem like it was forgotten, whereas including it makes it clear there is no associated effort. That was my thought process anyway, but that information is included in the sampling protocol as well, so I could go either way really.

**Comment by albenson-usgs** [comment]
Hmm...interesting. I'm not sure that downstream users would interpret it that way and it leads to extra rows in the emof table. I would just leave it out.

**Comment by Br-Johnson** [comment]
OK. Sounds good. I will remove it!
