### ISSUE TITLE
hakai_salmon_data: event numbers different

### ISSUE THREAD

**Issue by albenson-usgs** [marinebon/ioos_bio_data_scripts#6]
There are 695 eventIDs in the event file but only 435 in the occurrence file. Is it that not all the events have occurrences associated with them? If yes, why is that? Is it delineated in the data somewhere? Should we consider limiting the event file to only events with occurrences?

**Comment by Br-Johnson** [comment]
Yes. Some events have no occurrences. Not needed here so I'll remove. This was also the cause of missing lat/lons for occurrences
