### ISSUE TITLE
hakai_salmon_data: occurrenceID missing from eMoF file

### ISSUE THREAD

**Issue by albenson-usgs** [marinebon/ioos_bio_data_scripts#9]
occurrenceID is blank for all the rows in the measurement or fact file. Is this accurate? None of the measurements are for particular occurrences? They are only measurements of the events? This doesn't seem right as the measurementType length must be for particular occurrences?

**Comment by Br-Johnson** [comment]
The measurements only relate to the event in the case of catch abundance by species. A seine (setting of the seine net) is what defines the event. The occurrence is each fish. So in this case, you and I decided in Ann Arbour that a field in the `measurementOrFact` table could have rows that have measurements or facts about only the events, and not the occurrences. Does that still sound right?

**Comment by albenson-usgs** [comment]
Oh ok. That makes sense then. I wonder if there is some way to make this clearer.

**Comment by Br-Johnson** [comment]
I think it comes down to whether I consider 1 fish an occurrence, or consider the seine as the occurrence rather than the event. 

Trade-offs aren't clear at this stage but I will investigate. I think it comes down to how to deal with measurements or facts about a specific fish.

**Comment by Br-Johnson** [comment]
Or perhaps it's better to have a separate eMoF table that relates only to the event. That's kind of looks like how it's supposed to be structured based on the OBIS-ENV data format diagram

![Screen Shot 2019-11-13 at 11 36 55 AM](https://user-images.githubusercontent.com/26495640/68797697-ea15f000-0609-11ea-85ac-91172a12ccd8.png)

**Comment by albenson-usgs** [comment]
I agree that this diagram makes it come across that way but in fact those are both the same file- it's just hard to diagram measurements coming off the event and occurrence in the same column.

Maybe we just need to group the occurrences of one species together? It's definitely possible to have an occurrence row that has scientificName = Oncorhynchus keta and individualCount = 23. If you don't have any measurements for each individual fish then there is no need to have each one of those as a unique row/occurrence.

**Comment by Br-Johnson** [comment]
Yep, that makes sense! I'll do that.

**Comment by Br-Johnson** [comment]
I realized there isn't actually much point to including a summary of catch per seine by species. That can be calculated from the occurrence table so long as I include all fish caught as an occurrence, not just those fish that were just retained and will have subsequent measurementsOrFacts.
